allowBuilds:
  '@ast-grep/lang-go': true
  '@ast-grep/lang-php': true
  '@ast-grep/lang-python': true
  '@ast-grep/lang-ruby': true
  '@ast-grep/lang-rust': true
  better-sqlite3: true
  electron: true
  esbuild: true
  node-pty: true
  opencode-ai: true
  svelte-preprocess: true
