/**
 * agentCliProvision — puts the `slipstream` CLI on agent PATHs (FLO-104).
 *
 * One static POSIX wrapper script at `<dataDir>/bin/slipstream` execs the
 * bundled CLI under Electron-as-Node (the CLI shares better-sqlite3 with the
 * daemon, so it must run on Electron's ABI). Each session PTY then gets
 * `PATH=<binDir>:<daemon PATH>` plus the four SLIPSTREAM_* identity vars.
 * None of these values are secrets — SLIPSTREAM_TOKEN and the other daemon
 * internals stay scrubbed by agentEnv.ts, which the env built here passes
 * through unchanged.
 *
 * POSIX-only (sh wrapper): the app targets Linux/macOS only.
 */
import * as fs from 'node:fs'
import * as path from 'node:path'

export interface CliProvisionParams {
  electronPath: string
  cliJsPath: string
  binDir: string
}

export interface CliSessionEnvParams {
  dataDir: string
  sessionId: string
  base: string
  branch: string
  binDir: string
  /** The daemon's PATH — buildAgentEnv overrides replace PATH wholesale, so
   *  the wrapper dir must be composed with the full inherited value here. */
  basePath: string
}

/** The wrapper script content. `export` (not inline assignment) so the var
 *  reliably reaches the exec'd binary under any POSIX sh. */
export function wrapperScript(electronPath: string, cliJsPath: string): string {
  return `#!/bin/sh
# slipstream agent CLI wrapper — generated by the Slipstream daemon (FLO-104).
export ELECTRON_RUN_AS_NODE=1
exec "${electronPath}" "${cliJsPath}" "$@"
`
}

/** Write (or refresh) the wrapper at `<binDir>/slipstream`, mode 755.
 *  Idempotent; throws on fs errors — callers decide whether that's fatal. */
export function provisionCliWrapper(params: CliProvisionParams): string {
  const wrapperPath = path.join(params.binDir, 'slipstream')
  fs.mkdirSync(params.binDir, { recursive: true })
  fs.writeFileSync(wrapperPath, wrapperScript(params.electronPath, params.cliJsPath), {
    mode: 0o755,
  })
  // writeFileSync's mode only applies on create — chmod covers refreshes.
  fs.chmodSync(wrapperPath, 0o755)
  return wrapperPath
}

/** Per-session PTY env: CLI identity vars + PATH with the wrapper dir prepended. */
export function buildCliSessionEnv(params: CliSessionEnvParams): Record<string, string> {
  return {
    SLIPSTREAM_DATA_DIR: params.dataDir,
    SLIPSTREAM_SESSION_ID: params.sessionId,
    SLIPSTREAM_BASE: params.base,
    SLIPSTREAM_BRANCH: params.branch,
    PATH: params.basePath ? `${params.binDir}:${params.basePath}` : params.binDir,
  }
}

/** The IpcDeps.agentCli dependency bag (see electron/ipc.ts). */
export interface AgentCliDep {
  binDir: string
  cliJsPath: string
  electronPath: string
  dataDir: string
}

/**
 * The one env-builder shared by sessionLauncher and rpc's resume /
 * remote-control / handoff paths (was triplicated MCP-config writing).
 * Returns undefined when there's nothing to set, matching the callers'
 * "omit env entirely" convention.
 */
export function agentSessionEnv(
  agentCli: AgentCliDep | undefined,
  opts: { sessionId: string; base: string; branch: string; port?: number },
): Record<string, string> | undefined {
  const env: Record<string, string> = {}
  if (opts.port !== undefined) env.PORT = String(opts.port)
  if (agentCli) {
    Object.assign(
      env,
      buildCliSessionEnv({
        dataDir: agentCli.dataDir,
        sessionId: opts.sessionId,
        base: opts.base,
        branch: opts.branch,
        binDir: agentCli.binDir,
        basePath: process.env.PATH ?? '',
      }),
    )
  }
  return Object.keys(env).length > 0 ? env : undefined
}
