/**
 * agentCliProvision — puts the `slipstream` CLI on agent PATHs (FLO-104).
 *
 * One static POSIX wrapper script at `<dataDir>/bin/slipstream` execs the
 * bundled CLI under Electron-as-Node (the CLI shares better-sqlite3 with the
 * daemon, so it must run on Electron's ABI). Each session PTY then gets
 * `PATH=<binDir>:<daemon PATH>` plus the four SLIPSTREAM_* identity vars.
 * None of these values are secrets — SLIPSTREAM_TOKEN and the other daemon
 * internals stay scrubbed by agentEnv.ts, which the env built here passes
 * through unchanged.
 *
 * POSIX-only (sh wrapper): the app targets Linux/macOS only.
 */
import * as fs from 'node:fs'
import * as path from 'node:path'

export interface CliProvisionParams {
  electronPath: string
  cliJsPath: string
  binDir: string
}

export interface CliSessionEnvParams {
  dataDir: string
  sessionId: string
  base: string
  branch: string
  binDir: string
  /** The daemon's PATH — buildAgentEnv overrides replace PATH wholesale, so
   *  the wrapper dir must be composed with the full inherited value here. */
  basePath: string
}

/** The wrapper script content. `export` (not inline assignment) so the var
 *  reliably reaches the exec'd binary under any POSIX sh. */
export function wrapperScript(electronPath: string, cliJsPath: string): string {
  return `#!/bin/sh
# slipstream agent CLI wrapper — generated by the Slipstream daemon (FLO-104).
export ELECTRON_RUN_AS_NODE=1
exec "${electronPath}" "${cliJsPath}" "$@"
`
}

/** Write (or refresh) the wrapper at `<binDir>/slipstream`, mode 755.
 *  Idempotent; throws on fs errors — callers decide whether that's fatal. */
export function provisionCliWrapper(params: CliProvisionParams): string {
  const wrapperPath = path.join(params.binDir, 'slipstream')
  fs.mkdirSync(params.binDir, { recursive: true })
  fs.writeFileSync(wrapperPath, wrapperScript(params.electronPath, params.cliJsPath), {
    mode: 0o755,
  })
  // writeFileSync's mode only applies on create — chmod covers refreshes.
  fs.chmodSync(wrapperPath, 0o755)
  return wrapperPath
}

/** Per-session PTY env: CLI identity vars + PATH with the wrapper dir prepended. */
export function buildCliSessionEnv(params: CliSessionEnvParams): Record<string, string> {
  return {
    SLIPSTREAM_DATA_DIR: params.dataDir,
    SLIPSTREAM_SESSION_ID: params.sessionId,
    SLIPSTREAM_BASE: params.base,
    SLIPSTREAM_BRANCH: params.branch,
    PATH: params.basePath ? `${params.binDir}:${params.basePath}` : params.binDir,
  }
}

/** The IpcDeps.agentCli dependency bag (see electron/ipc.ts). */
export interface AgentCliDep {
  binDir: string
  cliJsPath: string
  electronPath: string
  dataDir: string
}

/**
 * The one env-builder shared by sessionLauncher and rpc's resume /
 * remote-control / handoff paths (was triplicated MCP-config writing).
 * Returns undefined when there's nothing to set, matching the callers'
 * "omit env entirely" convention.
 */
export function agentSessionEnv(
  agentCli: AgentCliDep | undefined,
  opts: { sessionId: string; base: string; branch: string; port?: number },
): Record<string, string> | undefined {
  const env: Record<string, string> = {}
  if (opts.port !== undefined) env.PORT = String(opts.port)
  if (agentCli) {
    Object.assign(
      env,
      buildCliSessionEnv({
        dataDir: agentCli.dataDir,
        sessionId: opts.sessionId,
        base: opts.base,
        branch: opts.branch,
        binDir: agentCli.binDir,
        basePath: process.env.PATH ?? '',
      }),
    )
  }
  return Object.keys(env).length > 0 ? env : undefined
}

/**
 * Clipboard-tool shims (TASK-CWLL6) — an OSC 52 bridge for CLI clipboard
 * access inside a headless/remote agent PTY.
 *
 * Agent scripts on Linux/macOS commonly shell out to xclip/xsel/wl-copy/
 * wl-paste/pbcopy/pbpaste for clipboard access. None of those tools exist in
 * this remote environment, so those calls would otherwise fail outright.
 * These shims install POSIX-sh replacements of the same names into the same
 * PATH-prepended `binDir` that `provisionCliWrapper` already uses (additive;
 * that function's behavior is unchanged). On write, they read stdin and emit
 * it as an OSC 52 escape sequence to /dev/tty — inside a PTY child, /dev/tty
 * *is* the pty device, so the sequence reaches the viewer's terminal, where
 * the renderer's OSC 52 handler writes it to the local clipboard. On read,
 * they serve back the most recently OSC-52-cached clipboard image, if one
 * exists and an image target was explicitly requested; plain-text reads have
 * no server-side source of truth and always return empty.
 *
 * These scripts must never fail the calling script: unrecognized flags are
 * swallowed, and every path — including an unwritable /dev/tty — ends in
 * `exit 0`.
 */

export type ClipboardShimTool = 'xclip' | 'xsel' | 'wl-copy' | 'wl-paste' | 'pbcopy' | 'pbpaste'

const CLIPBOARD_SHIM_TOOLS: readonly ClipboardShimTool[] = [
  'xclip',
  'xsel',
  'wl-copy',
  'wl-paste',
  'pbcopy',
  'pbpaste',
]

function shimHeader(tool: string): string {
  return `#!/bin/sh
# ${tool} shim — OSC 52 clipboard bridge, generated by the Slipstream daemon
# (TASK-CWLL6). Real ${tool} doesn't exist in this headless/remote
# environment; this script stands in for it so agent scripts calling it
# transparently get clipboard access via the viewer's terminal instead of a
# hard failure. Never exits nonzero.
`
}

/** Reads stdin (capped at 5 MiB so a runaway pipe can't flood the terminal),
 *  base64-encodes it, and emits it as an OSC 52 "set clipboard" escape
 *  sequence (target `c`, BEL-terminated) to $SLIPSTREAM_TTY_OVERRIDE if set,
 *  else /dev/tty. The override exists only so tests can redirect this write
 *  away from a real tty — /dev/tty isn't reliably openable/redirectable
 *  under a test harness. If the target can't be opened, fail silently: the
 *  subshell absorbs the error and `|| true` plus the unconditional `exit 0`
 *  guarantee the calling script never sees a nonzero exit. */
const WRITE_BODY = `b64=$(head -c 5242880 | base64 | tr -d '\\n')
tty_target="\${SLIPSTREAM_TTY_OVERRIDE:-/dev/tty}"
(printf '\\033]52;c;%s\\007' "$b64" > "$tty_target") 2>/dev/null || true
exit 0
`

/** Shared read-mode dispatch for xclip/xsel-style `-t TARGET` parsing:
 *  `-t TARGETS` lists the cached image's mime type (if present), an explicit
 *  image target cats the cached file (if present), anything else — plain
 *  text, or no cached file — prints nothing. Always exits 0. */
const READ_TARGET_BODY = `png="$SLIPSTREAM_DATA_DIR/clipboard/$SLIPSTREAM_SESSION_ID.png"
case "$target" in
  TARGETS)
    [ -f "$png" ] && echo image/png
    ;;
  image/png|image/*)
    [ -f "$png" ] && cat "$png"
    ;;
esac
exit 0
`

/** xclip/xsel share flag conventions: write by default (or explicit
 *  -i/--input), read on -o/--output; -t TARGET carries the requested target
 *  for read mode. Unrecognized flags are simply not matched by the case
 *  statements above and fall through harmlessly. */
function xclipLikeScript(tool: 'xclip' | 'xsel'): string {
  return `${shimHeader(tool)}
mode="write"
target=""
prev=""
for arg in "$@"; do
  case "$prev" in
    -t) target="$arg" ;;
  esac
  case "$arg" in
    -o|--output) mode="read" ;;
    -i|--input) mode="write" ;;
  esac
  prev="$arg"
done

if [ "$mode" = "read" ]; then
${READ_TARGET_BODY}fi

${WRITE_BODY}`
}

/** wl-paste is always read mode; `--type X` / `--type=X` requests a target,
 *  `--list-types` lists available targets. Same semantics as the xclip -t
 *  handling above, just wl-paste's own flag spelling. */
function wlPasteScript(): string {
  return `${shimHeader('wl-paste')}
target=""
list_types=0
prev=""
for arg in "$@"; do
  case "$prev" in
    --type) target="$arg" ;;
  esac
  case "$arg" in
    --type=*) target="\${arg#--type=}" ;;
    --list-types) list_types=1 ;;
  esac
  prev="$arg"
done

png="$SLIPSTREAM_DATA_DIR/clipboard/$SLIPSTREAM_SESSION_ID.png"
if [ "$list_types" = "1" ]; then
  [ -f "$png" ] && echo image/png
  exit 0
fi
case "$target" in
  image/png|image/*)
    [ -f "$png" ] && cat "$png"
    ;;
esac
exit 0
`
}

/** wl-copy/pbcopy have no read mode at all — every invocation writes,
 *  regardless of any flags passed (which are ignored). */
function writeOnlyScript(tool: 'wl-copy' | 'pbcopy'): string {
  return `${shimHeader(tool)}
${WRITE_BODY}`
}

/** pbpaste has no target-flag mechanism (unlike xclip/wl-paste), so per the
 *  ticket spec it never surfaces the cached image — always prints nothing. */
function pbpasteScript(): string {
  return `${shimHeader('pbpaste')}
exit 0
`
}

/** The shim script content for one clipboard tool name (mirrors
 *  `wrapperScript`'s role for the `slipstream` CLI wrapper). */
export function clipboardShimScript(tool: ClipboardShimTool): string {
  switch (tool) {
    case 'xclip':
    case 'xsel':
      return xclipLikeScript(tool)
    case 'wl-paste':
      return wlPasteScript()
    case 'wl-copy':
    case 'pbcopy':
      return writeOnlyScript(tool)
    case 'pbpaste':
      return pbpasteScript()
  }
}

/** Write (or refresh) all six clipboard shims into `binDir`, mode 755 —
 *  same idempotent write+chmod pattern as `provisionCliWrapper`. Additive to
 *  that function; does not change its behavior or call sites. Returns the
 *  paths written. */
export function provisionClipboardShims(binDir: string): string[] {
  fs.mkdirSync(binDir, { recursive: true })
  return CLIPBOARD_SHIM_TOOLS.map((tool) => {
    const shimPath = path.join(binDir, tool)
    fs.writeFileSync(shimPath, clipboardShimScript(tool), { mode: 0o755 })
    // writeFileSync's mode only applies on create — chmod covers refreshes.
    fs.chmodSync(shimPath, 0o755)
    return shimPath
  })
}
